alias: CO2 in de keuken 2
description: ""
triggers:
  - entity_id: sensor.s1_pro_multi_sense_97b4f8_scd40_co2_concentration
    trigger: state
actions:
  - variables:
      co2: >-
        {{ states('sensor.s1_pro_multi_sense_97b4f8_scd40_co2_concentration') |
        float(-1) }}
      present: >-
        {{ is_state('binary_sensor.s1_pro_multi_sense_97b4f8_any_presence',
        'on') }}
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ not present or co2 < 0 }}"
        sequence:
          - target:
              entity_id: light.s1_pro_multi_sense_97b4f8_ws2812_led
            action: light.turn_off
      - conditions:
          - condition: template
            value_template: "{{ co2 < 1000 }}"
        sequence:
          - data:
              rgb_color:
                - 0
                - 255
                - 0
            target:
              entity_id: light.s1_pro_multi_sense_97b4f8_ws2812_led
            action: light.turn_on
      - conditions:
          - condition: template
            value_template: "{{ 1000 <= co2 < 1400 }}"
        sequence:
          - data:
              rgb_color:
                - 255
                - 255
                - 0
            target:
              entity_id: light.s1_pro_multi_sense_97b4f8_ws2812_led
            action: light.turn_on
      - conditions:
          - condition: template
            value_template: "{{ co2 >= 1400 }}"
        sequence:
          - data:
              rgb_color:
                - 255
                - 0
                - 0
            target:
              entity_id: light.s1_pro_multi_sense_97b4f8_ws2812_led
            action: light.turn_on
          - target:
              entity_id: switch.s1_pro_multi_sense_97b4f8_mlt8530_buzzer
            action: switch.turn_on
            data: {}
            enabled: false
          - delay: "00:00:02"
          - target:
              entity_id: switch.s1_pro_multi_sense_97b4f8_mlt8530_buzzer
            action: switch.turn_off
mode: restart
