alias: co2 keuken v2
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.s1_pro_multi_sense_97b4f8_scd40_co2_concentration
conditions: []
actions:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.s1_pro_multi_sense_97b4f8_scd40_co2_concentration
            below: 1000
        sequence:
          - action: light.turn_on
            metadata: {}
            data:
              rgb_color:
                - 0
                - 255
                - 0
            target:
              entity_id: light.s1_pro_multi_sense_97b4f8_ws2812_led
      - conditions:
          - condition: numeric_state
            entity_id: sensor.s1_pro_multi_sense_97b4f8_scd40_co2_concentration
            below: 1400
            above: 1000
        sequence:
          - action: light.turn_on
            metadata: {}
            data:
              rgb_color:
                - 255
                - 255
                - 0
            target:
              entity_id: light.s1_pro_multi_sense_97b4f8_ws2812_led
      - conditions:
          - condition: numeric_state
            entity_id: sensor.s1_pro_multi_sense_97b4f8_scd40_co2_concentration
            above: 1400
        sequence:
          - action: light.turn_on
            metadata: {}
            data:
              rgb_color:
                - 255
                - 0
                - 0
            target:
              entity_id: light.s1_pro_multi_sense_97b4f8_ws2812_led
mode: single
